###PLOT PARAM RANGES###

#library(plotrix)


#setup directory structure
Sys.info()

#any mac
if(.Platform$OS.type=="unix"){
	root_dir <- path.expand("~/Dropbox/ktp/PPTCompPaper/")
}

#windows
if(.Platform$OS.type=="windows"){
	root_dir <- path.expand("d://Dropbox/ktp/PPTCompPaper/")
}

Calib.Ranges <- read.csv(paste(root_dir,"paramranges.csv", sep=""), header=T)
Param.Names <- Calib.Ranges[,1]
Calib.Ranges <- Calib.Ranges[,-1]

pdf(paste(root_dir,"paramranges.pdf", sep=""),height=8,width=2.5, colormodel="cmyk")
par(mfrow = c(12,1), mai=c(0.075,0.075,0.075,0.075), mgp=c(2,1,0), omi=c(0.3,0.45,0.1,0.1))
#plot CN_2
for(i in 1:8){
		assign(paste("x",i,sep=""), c(i,i))
		assign(paste("y",i,sep=""), c(Calib.Ranges[1,(2*i-1)], Calib.Ranges[1,2*i]))
	  assign(paste("a",i,sep=""), c((i-0.08),(i+0.08)))
    assign(paste("b",i,sep=""), c(Calib.Ranges[1,(2*i-1)], Calib.Ranges[1,(2*i-1)]))
    assign(paste("c",i,sep=""), c(Calib.Ranges[1,2*i], Calib.Ranges[1,2*i]))
  }
#these 6 lines force CN max and min values to 1,-1
#y2 <- c(1, Calib.Ranges[1,(2*i-1)])
#y4 <- c(1, Calib.Ranges[1,(2*i-1)])
#y5 <- c(Calib.Ranges[1,2*i], -1)
c2 <- c(1.05,1.05)
c4 <- c(1.05,1.05)
b5 <- c(-1.05,-1.05)

plot(x1, y1, type="l", xlim=c(1,8), ylim=c(-1,1), xaxt="n", yaxt="n", xlab=NA, lwd=1, lend=1,col="orangered3")
  lines(a1, b1, type="l", lend=1, col="orangered3")
  lines(a1, c1, type="l", lend=1, col="orangered3")
	lines(x2, y2, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a2, b2, type="l", lend=1, col="darkcyan")
  lines(a2, c2, type="l", lend=1, col="darkcyan")  
  lines(x3, y3, type="l", lwd=1, lend=1,col="orangered3")
  lines(a3, b3, type="l", lend=1, col="orangered3")
  lines(a3, c3, type="l", lend=1, col="orangered3")
	lines(x4, y4, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a4, b4, type="l", lend=1, col="darkcyan")
  lines(a4, c4, type="l", lend=1, col="darkcyan")
  lines(x5, y5, type="l", lwd=1, lend=1,col="orangered3")
  lines(a5, b5, type="l", lend=1, col="orangered3")
  lines(a5, c5, type="l", lend=1, col="orangered3")
	lines(x6, y6, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a6, b6, type="l", lend=1, col="darkcyan")
  lines(a6, c6, type="l", lend=1, col="darkcyan")
	lines(x7, y7, type="l", lwd=1, lend=1,col="orangered3")
  lines(a7, b7, type="l", lend=1, col="orangered3")
  lines(a7, c7, type="l", lend=1, col="orangered3")
	lines(x8, y8, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a8, b8, type="l", lend=1, col="darkcyan")
  lines(a8, c8, type="l", lend=1, col="darkcyan")
	axis(2,at=c(-1.0,-0.5,0,0.5,1.0),labels=c(-1.0,-0.5,0,0.5,1.0), padj=0.4, cex.axis=0.7)
mtext("CN_2", side=2, padj=-4, cex=0.5)

#plot Alpha_Bf
for(i in 1:8){
	  assign(paste("x",i,sep=""), c(i,i))
	  assign(paste("y",i,sep=""), c(Calib.Ranges[2,(2*i-1)], Calib.Ranges[2,2*i]))
	  assign(paste("a",i,sep=""), c((i-0.08),(i+0.08)))
    assign(paste("b",i,sep=""), c(Calib.Ranges[2,(2*i-1)], Calib.Ranges[2,(2*i-1)]))
    assign(paste("c",i,sep=""), c(Calib.Ranges[2,2*i], Calib.Ranges[2,2*i]))
  }
	#plot(x1, y1, type="l", main="", xlab="", ylab="ALPHA_BF", xlim=c(1,8), ylim=c(min(Calib.Ranges[2,]),max(Calib.Ranges[2,])))
plot(x1, y1, type="l", xlim=c(1,8), ylim=c(0.0,3), yaxt="n", xaxt="n", xlab=NA, ylab="Aplha+BF", lwd=1, lend=1,col="orangered3")
  lines(a1, b1, type="l", lend=1, col="orangered3")
  lines(a1, c1, type="l", lend=1, col="orangered3")
  lines(x2, y2, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a2, b2, type="l", lend=1, col="darkcyan")
  lines(a2, c2, type="l", lend=1, col="darkcyan")  
  lines(x3, y3, type="l", lwd=1, lend=1,col="orangered3")
  lines(a3, b3, type="l", lend=1, col="orangered3")
  lines(a3, c3, type="l", lend=1, col="orangered3")
	lines(x4, y4, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a4, b4, type="l", lend=1, col="darkcyan")
  lines(a4, c4, type="l", lend=1, col="darkcyan")
  lines(x5, y5, type="l", lwd=1, lend=1,col="orangered3")
  lines(a5, b5, type="l", lend=1, col="orangered3")
  lines(a5, c5, type="l", lend=1, col="orangered3")
	lines(x6, y6, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a6, b6, type="l", lend=1, col="darkcyan")
  lines(a6, c6, type="l", lend=1, col="darkcyan")
	lines(x7, y7, type="l", lwd=1, lend=1,col="orangered3")
  lines(a7, b7, type="l", lend=1, col="orangered3")
  lines(a7, c7, type="l", lend=1, col="orangered3")
	lines(x8, y8, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a8, b8, type="l", lend=1, col="darkcyan")
  lines(a8, c8, type="l", lend=1, col="darkcyan")
	axis(2,at=c(0,1,2,3),labels=c(0,1,2,3), padj=0.4, cex.axis=0.7)
mtext("ALPHA_BF", side=2, padj=-4, cex=0.5)	

#plot 3 GW_REVAP
for(i in 1:8){
	assign(paste("x",i,sep=""), c(i,i))
	assign(paste("y",i,sep=""), c(Calib.Ranges[3,(2*i-1)], Calib.Ranges[3,2*i]))
  assign(paste("a",i,sep=""), c((i-0.08),(i+0.08)))
  assign(paste("b",i,sep=""), c(Calib.Ranges[3,(2*i-1)], Calib.Ranges[3,(2*i-1)]))
  assign(paste("c",i,sep=""), c(Calib.Ranges[3,2*i], Calib.Ranges[3,2*i]))
	}
	#plot(x1, y1, type="l", main="", xlab="", ylab="GWREVAP", xlim=c(1,8), ylim=c(min(Calib.Ranges[3,]),max(Calib.Ranges[3,])))
	plot(x1, y1, type="l", xlim=c(1,8), ylim=c(0.02,0.2), yaxt="n", xaxt="n", xlab=NA, lwd=1, lend=1,col="orangered3")
  lines(a1, b1, type="l", lend=1, col="orangered3")
  lines(a1, c1, type="l", lend=1, col="orangered3")
  lines(x2, y2, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a2, b2, type="l", lend=1, col="darkcyan")
  lines(a2, c2, type="l", lend=1, col="darkcyan")  
  lines(x3, y3, type="l", lwd=1, lend=1,col="orangered3")
  lines(a3, b3, type="l", lend=1, col="orangered3")
  lines(a3, c3, type="l", lend=1, col="orangered3")
	lines(x4, y4, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a4, b4, type="l", lend=1, col="darkcyan")
  lines(a4, c4, type="l", lend=1, col="darkcyan")
  lines(x5, y5, type="l", lwd=1, lend=1,col="orangered3")
  lines(a5, b5, type="l", lend=1, col="orangered3")
  lines(a5, c5, type="l", lend=1, col="orangered3")
	lines(x6, y6, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a6, b6, type="l", lend=1, col="darkcyan")
  lines(a6, c6, type="l", lend=1, col="darkcyan")
	lines(x7, y7, type="l", lwd=1, lend=1,col="orangered3")
  lines(a7, b7, type="l", lend=1, col="orangered3")
  lines(a7, c7, type="l", lend=1, col="orangered3")
	lines(x8, y8, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a8, b8, type="l", lend=1, col="darkcyan")
  lines(a8, c8, type="l", lend=1, col="darkcyan")
	axis(2,at=c(0,0.1,0.2),labels=c(0,0.1,0.2), padj=0.4, cex.axis=0.7)
mtext("GW_REVAP", side=2, padj=-4, cex=0.5)
	
#plot 4 CH_N2
for(i in 1:8){
	assign(paste("x",i,sep=""), c(i,i))
	assign(paste("y",i,sep=""), c(Calib.Ranges[4,(2*i-1)], Calib.Ranges[4,2*i]))
  assign(paste("a",i,sep=""), c((i-0.08),(i+0.08)))
  assign(paste("b",i,sep=""), c(Calib.Ranges[4,(2*i-1)], Calib.Ranges[4,(2*i-1)]))
  assign(paste("c",i,sep=""), c(Calib.Ranges[4,2*i], Calib.Ranges[4,2*i]))
	}
	#plot(x1, y1, type="l", main="", xlab="", ylab="CH_N2", xlim=c(1,8), ylim=c(min(Calib.Ranges[4,]),max(Calib.Ranges[4,])))
plot(x1, y1, type="l", xlim=c(1,8), ylim=c(0.0,0.30), yaxt="n", xaxt="n", xlab=NA, lwd=1, lend=1,col="orangered3")
	  lines(a1, b1, type="l", lend=1, col="orangered3")
  lines(a1, c1, type="l", lend=1, col="orangered3")
  lines(x2, y2, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a2, b2, type="l", lend=1, col="darkcyan")
  lines(a2, c2, type="l", lend=1, col="darkcyan")  
  lines(x3, y3, type="l", lwd=1, lend=1,col="orangered3")
  lines(a3, b3, type="l", lend=1, col="orangered3")
  lines(a3, c3, type="l", lend=1, col="orangered3")
	lines(x4, y4, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a4, b4, type="l", lend=1, col="darkcyan")
  lines(a4, c4, type="l", lend=1, col="darkcyan")
  lines(x5, y5, type="l", lwd=1, lend=1,col="orangered3")
  lines(a5, b5, type="l", lend=1, col="orangered3")
  lines(a5, c5, type="l", lend=1, col="orangered3")
	lines(x6, y6, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a6, b6, type="l", lend=1, col="darkcyan")
  lines(a6, c6, type="l", lend=1, col="darkcyan")
	lines(x7, y7, type="l", lwd=1, lend=1,col="orangered3")
  lines(a7, b7, type="l", lend=1, col="orangered3")
  lines(a7, c7, type="l", lend=1, col="orangered3")
	lines(x8, y8, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a8, b8, type="l", lend=1, col="darkcyan")
  lines(a8, c8, type="l", lend=1, col="darkcyan")
	axis(2,at=c(0.1,0.3),labels=c(0.1,0.3), padj=0.4, cex.axis=0.7)
mtext("CH_N2", side=2, padj=-4, cex=0.5)

#plot 5 CH_K2
for(i in 1:8){
	assign(paste("x",i,sep=""), c(i,i))
	assign(paste("y",i,sep=""), c(Calib.Ranges[5,(2*i-1)], Calib.Ranges[5,2*i]))
  assign(paste("a",i,sep=""), c((i-0.08),(i+0.08)))
  assign(paste("b",i,sep=""), c(Calib.Ranges[5,(2*i-1)], Calib.Ranges[5,(2*i-1)]))
  assign(paste("c",i,sep=""), c(Calib.Ranges[5,2*i], Calib.Ranges[5,2*i]))
}
#plot(x1, y1, type="l", main="", xlab="", ylab="CH_K2", xlim=c(1,8), ylim=c(min(Calib.Ranges[5,]),max(Calib.Ranges[5,])))
plot(x1, y1, type="l", xlim=c(1,8), ylim=c(-0.01,150), yaxt="n", xaxt="n", xlab=NA, lwd=1, lend=1,col="orangered3")
  lines(a1, b1, type="l", lend=1, col="orangered3")
  lines(a1, c1, type="l", lend=1, col="orangered3")
  lines(x2, y2, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a2, b2, type="l", lend=1, col="darkcyan")
  lines(a2, c2, type="l", lend=1, col="darkcyan")  
  lines(x3, y3, type="l", lwd=1, lend=1,col="orangered3")
  lines(a3, b3, type="l", lend=1, col="orangered3")
  lines(a3, c3, type="l", lend=1, col="orangered3")
	lines(x4, y4, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a4, b4, type="l", lend=1, col="darkcyan")
  lines(a4, c4, type="l", lend=1, col="darkcyan")
  lines(x5, y5, type="l", lwd=1, lend=1,col="orangered3")
  lines(a5, b5, type="l", lend=1, col="orangered3")
  lines(a5, c5, type="l", lend=1, col="orangered3")
	lines(x6, y6, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a6, b6, type="l", lend=1, col="darkcyan")
  lines(a6, c6, type="l", lend=1, col="darkcyan")
	lines(x7, y7, type="l", lwd=1, lend=1,col="orangered3")
  lines(a7, b7, type="l", lend=1, col="orangered3")
  lines(a7, c7, type="l", lend=1, col="orangered3")
	lines(x8, y8, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a8, b8, type="l", lend=1, col="darkcyan")
  lines(a8, c8, type="l", lend=1, col="darkcyan")
axis(2,at=c(0,75,150),labels=c(0,75,150), padj=0.4, cex.axis=0.7)
mtext("CH_K2", side=2, padj=-4, cex=0.5)

#plot 6 GWQMN
for(i in 1:8){
	assign(paste("x",i,sep=""), c(i,i))
	assign(paste("y",i,sep=""), c(Calib.Ranges[6,(2*i-1)], Calib.Ranges[6,2*i]))
  assign(paste("a",i,sep=""), c((i-0.08),(i+0.08)))
  assign(paste("b",i,sep=""), c(Calib.Ranges[6,(2*i-1)], Calib.Ranges[6,(2*i-1)]))
  assign(paste("c",i,sep=""), c(Calib.Ranges[6,2*i], Calib.Ranges[6,2*i]))
	}
plot(x1, y1, type="l", xlim=c(1,8), ylim=c(0,1000), yaxt="n", xaxt="n", xlab=NA, lwd=1, lend=1,col="orangered3")
	lines(a1, b1, type="l", lend=1, col="orangered3")
  lines(a1, c1, type="l", lend=1, col="orangered3")
  lines(x2, y2, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a2, b2, type="l", lend=1, col="darkcyan")
  lines(a2, c2, type="l", lend=1, col="darkcyan")  
  lines(x3, y3, type="l", lwd=1, lend=1,col="orangered3")
  lines(a3, b3, type="l", lend=1, col="orangered3")
  lines(a3, c3, type="l", lend=1, col="orangered3")
	lines(x4, y4, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a4, b4, type="l", lend=1, col="darkcyan")
  lines(a4, c4, type="l", lend=1, col="darkcyan")
  lines(x5, y5, type="l", lwd=1, lend=1,col="orangered3")
  lines(a5, b5, type="l", lend=1, col="orangered3")
  lines(a5, c5, type="l", lend=1, col="orangered3")
	lines(x6, y6, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a6, b6, type="l", lend=1, col="darkcyan")
  lines(a6, c6, type="l", lend=1, col="darkcyan")
	lines(x7, y7, type="l", lwd=1, lend=1,col="orangered3")
  lines(a7, b7, type="l", lend=1, col="orangered3")
  lines(a7, c7, type="l", lend=1, col="orangered3")
	lines(x8, y8, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a8, b8, type="l", lend=1, col="darkcyan")
  lines(a8, c8, type="l", lend=1, col="darkcyan")
	#axis(1,at=c(1,2,3,4,5,6,7,8),labels=c("GAUGE","RADAR","GAUGE","RADAR","GAUGE","RADAR","GAUGE","RADAR"), cex.axis=0.4, padj=-1)
  axis(2,at=c(250,750),labels=c(0,750), padj=0.4, cex.axis=0.7)
mtext("GWQMN", side=2, padj=-4, cex=0.5)

#plot 7 SOL_AWC
for(i in 1:8){
	assign(paste("x",i,sep=""), c(i,i))
	assign(paste("y",i,sep=""), c(Calib.Ranges[7,(2*i-1)], Calib.Ranges[7,2*i]))
  assign(paste("a",i,sep=""), c((i-0.08),(i+0.08)))
  assign(paste("b",i,sep=""), c(Calib.Ranges[7,(2*i-1)], Calib.Ranges[7,(2*i-1)]))
  assign(paste("c",i,sep=""), c(Calib.Ranges[7,2*i], Calib.Ranges[7,2*i]))
	}
	#plot(x1, y1, type="l", main="", xlab="", ylab="SOL_AWC", xlim=c(1,8), ylim=c(min(Calib.Ranges[7,]),max(Calib.Ranges[7,])))
plot(x1, y1, type="l", xlim=c(1,8), ylim=c(-0.2,0.6), xaxt="n", yaxt="n", xlab=NA, lwd=1, lend=1,col="orangered3")
  lines(a1, b1, type="l", lend=1, col="orangered3")
  lines(a1, c1, type="l", lend=1, col="orangered3")
  lines(x2, y2, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a2, b2, type="l", lend=1, col="darkcyan")
  lines(a2, c2, type="l", lend=1, col="darkcyan")  
  lines(x3, y3, type="l", lwd=1, lend=1,col="orangered3")
  lines(a3, b3, type="l", lend=1, col="orangered3")
  lines(a3, c3, type="l", lend=1, col="orangered3")
	lines(x4, y4, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a4, b4, type="l", lend=1, col="darkcyan")
  lines(a4, c4, type="l", lend=1, col="darkcyan")
  lines(x5, y5, type="l", lwd=1, lend=1,col="orangered3")
  lines(a5, b5, type="l", lend=1, col="orangered3")
  lines(a5, c5, type="l", lend=1, col="orangered3")
	lines(x6, y6, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a6, b6, type="l", lend=1, col="darkcyan")
  lines(a6, c6, type="l", lend=1, col="darkcyan")
	lines(x7, y7, type="l", lwd=1, lend=1,col="orangered3")
  lines(a7, b7, type="l", lend=1, col="orangered3")
  lines(a7, c7, type="l", lend=1, col="orangered3")
	lines(x8, y8, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a8, b8, type="l", lend=1, col="darkcyan")
  lines(a8, c8, type="l", lend=1, col="darkcyan")
	axis(2,at=c(-0.2,0.2,0.6),labels=c(-0.2,0.2,0.6), padj=0.4, cex.axis=0.7)
mtext("SOL_AWC", side=2, padj=-4, cex=0.5)

#plot 8 SOL_K
for(i in 1:8){
	assign(paste("x",i,sep=""), c(i,i))
	assign(paste("y",i,sep=""), c(Calib.Ranges[8,(2*i-1)], Calib.Ranges[8,2*i]))
  assign(paste("a",i,sep=""), c((i-0.08),(i+0.08)))
  assign(paste("b",i,sep=""), c(Calib.Ranges[8,(2*i-1)], Calib.Ranges[8,(2*i-1)]))
  assign(paste("c",i,sep=""), c(Calib.Ranges[8,2*i], Calib.Ranges[8,2*i]))
	}
	#plot(x1, y1, type="l", main="", xlab="", ylab="SOL_K", xlim=c(1,8), ylim=c(min(Calib.Ranges[8,]),max(Calib.Ranges[8,])))
plot(x1, y1, type="l", xlim=c(1,8), ylim=c(-0.5,0.5), xaxt="n", yaxt="n", xlab=NA, lwd=1, lend=1,col="orangered3")
	  lines(a1, b1, type="l", lend=1, col="orangered3")
  lines(a1, c1, type="l", lend=1, col="orangered3")
  lines(x2, y2, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a2, b2, type="l", lend=1, col="darkcyan")
  lines(a2, c2, type="l", lend=1, col="darkcyan")  
  lines(x3, y3, type="l", lwd=1, lend=1,col="orangered3")
  lines(a3, b3, type="l", lend=1, col="orangered3")
  lines(a3, c3, type="l", lend=1, col="orangered3")
	lines(x4, y4, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a4, b4, type="l", lend=1, col="darkcyan")
  lines(a4, c4, type="l", lend=1, col="darkcyan")
  lines(x5, y5, type="l", lwd=1, lend=1,col="orangered3")
  lines(a5, b5, type="l", lend=1, col="orangered3")
  lines(a5, c5, type="l", lend=1, col="orangered3")
	lines(x6, y6, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a6, b6, type="l", lend=1, col="darkcyan")
  lines(a6, c6, type="l", lend=1, col="darkcyan")
	lines(x7, y7, type="l", lwd=1, lend=1,col="orangered3")
  lines(a7, b7, type="l", lend=1, col="orangered3")
  lines(a7, c7, type="l", lend=1, col="orangered3")
	lines(x8, y8, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a8, b8, type="l", lend=1, col="darkcyan")
  lines(a8, c8, type="l", lend=1, col="darkcyan")
	axis(2,at=c(-0.4,0,0.4),labels=c(-0.4,0,0.4), padj=0.4, cex.axis=0.7)
mtext("SOL_K", side=2, padj=-4, cex=0.5)

#plot 9 SOL_Z
for(i in 1:8){
	assign(paste("x",i,sep=""), c(i,i))
	assign(paste("y",i,sep=""), c(Calib.Ranges[9,(2*i-1)], Calib.Ranges[9,2*i]))
  assign(paste("a",i,sep=""), c((i-0.08),(i+0.08)))
  assign(paste("b",i,sep=""), c(Calib.Ranges[9,(2*i-1)], Calib.Ranges[9,(2*i-1)]))
  assign(paste("c",i,sep=""), c(Calib.Ranges[9,2*i], Calib.Ranges[9,2*i]))
	}
	#plot(x1, y1, type="l", main="", xlab="", ylab="SOL_Z", xlim=c(1,8), ylim=c(min(Calib.Ranges[9,]),max(Calib.Ranges[9,])))
plot(x1, y1, type="l", xlim=c(1,8), ylim=c(-0.25,0.25), xaxt="n", yaxt="n", xlab=NA, lwd=1, lend=1,col="orangered3")
  lines(a1, b1, type="l", lend=1, col="orangered3")
  lines(a1, c1, type="l", lend=1, col="orangered3")
  lines(x2, y2, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a2, b2, type="l", lend=1, col="darkcyan")
  lines(a2, c2, type="l", lend=1, col="darkcyan")  
  lines(x3, y3, type="l", lwd=1, lend=1,col="orangered3")
  lines(a3, b3, type="l", lend=1, col="orangered3")
  lines(a3, c3, type="l", lend=1, col="orangered3")
	lines(x4, y4, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a4, b4, type="l", lend=1, col="darkcyan")
  lines(a4, c4, type="l", lend=1, col="darkcyan")
  lines(x5, y5, type="l", lwd=1, lend=1,col="orangered3")
  lines(a5, b5, type="l", lend=1, col="orangered3")
  lines(a5, c5, type="l", lend=1, col="orangered3")
	lines(x6, y6, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a6, b6, type="l", lend=1, col="darkcyan")
  lines(a6, c6, type="l", lend=1, col="darkcyan")
	lines(x7, y7, type="l", lwd=1, lend=1,col="orangered3")
  lines(a7, b7, type="l", lend=1, col="orangered3")
  lines(a7, c7, type="l", lend=1, col="orangered3")
	lines(x8, y8, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a8, b8, type="l", lend=1, col="darkcyan")
  lines(a8, c8, type="l", lend=1, col="darkcyan")
	axis(2,at=c(-0.2,0,0.2),labels=c(-0.2,0,0.2), padj=0.4, cex.axis=0.7)
mtext("SOL_Z", side=2, padj=-4, cex=0.5)

#plot 10 CANMX
for(i in 1:8){
	assign(paste("x",i,sep=""), c(i,i))
	assign(paste("y",i,sep=""), c(Calib.Ranges[10,(2*i-1)], Calib.Ranges[10,2*i]))
  assign(paste("a",i,sep=""), c((i-0.08),(i+0.08)))
  assign(paste("b",i,sep=""), c(Calib.Ranges[10,(2*i-1)], Calib.Ranges[10,(2*i-1)]))
  assign(paste("c",i,sep=""), c(Calib.Ranges[10,2*i], Calib.Ranges[10,2*i]))
	}
	#plot(x1, y1, type="l", main="", xlab="", ylab="CANMX", xlim=c(1,8), ylim=c(min(Calib.Ranges[10,]),max(Calib.Ranges[10,])))
plot(x1, y1, type="l", xlim=c(1,8), ylim=c(0,25), padj=0.5, xaxt="n", yaxt="n", xlab=NA, lwd=1, lend=1,col="orangered3")
	lines(a1, b1, type="l", lend=1, col="orangered3")
  lines(a1, c1, type="l", lend=1, col="orangered3")
  lines(x2, y2, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a2, b2, type="l", lend=1, col="darkcyan")
  lines(a2, c2, type="l", lend=1, col="darkcyan")  
  lines(x3, y3, type="l", lwd=1, lend=1,col="orangered3")
  lines(a3, b3, type="l", lend=1, col="orangered3")
  lines(a3, c3, type="l", lend=1, col="orangered3")
	lines(x4, y4, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a4, b4, type="l", lend=1, col="darkcyan")
  lines(a4, c4, type="l", lend=1, col="darkcyan")
  lines(x5, y5, type="l", lwd=1, lend=1,col="orangered3")
  lines(a5, b5, type="l", lend=1, col="orangered3")
  lines(a5, c5, type="l", lend=1, col="orangered3")
	lines(x6, y6, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a6, b6, type="l", lend=1, col="darkcyan")
  lines(a6, c6, type="l", lend=1, col="darkcyan")
	lines(x7, y7, type="l", lwd=1, lend=1,col="orangered3")
  lines(a7, b7, type="l", lend=1, col="orangered3")
  lines(a7, c7, type="l", lend=1, col="orangered3")
	lines(x8, y8, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a8, b8, type="l", lend=1, col="darkcyan")
  lines(a8, c8, type="l", lend=1, col="darkcyan")
	axis(2,at=c(0,10,20),labels=c(0,10,20), padj=0.4, cex.axis=0.7)
mtext("CANMX", side=2, padj=-4, cex=0.5)

#plot 11 ESCO
for(i in 1:8){
	assign(paste("x",i,sep=""), c(i,i))
	assign(paste("y",i,sep=""), c(Calib.Ranges[11,(2*i-1)], Calib.Ranges[11,2*i]))
  assign(paste("a",i,sep=""), c((i-0.08),(i+0.08)))
  assign(paste("b",i,sep=""), c(Calib.Ranges[11,(2*i-1)], Calib.Ranges[11,(2*i-1)]))
  assign(paste("c",i,sep=""), c(Calib.Ranges[11,2*i], Calib.Ranges[11,2*i]))
	}
	#plot(x1, y1, type="l", main="", xlab="", ylab="ESCO", xlim=c(1,8), ylim=c(min(Calib.Ranges[11,]),max(Calib.Ranges[11,])))
plot(x1, y1, type="l", xlim=c(1,8), ylim=c(0.001,1), yaxt="n", xaxt="n", xlab=NA, lwd=1, lend=1,col="orangered3")
  lines(a1, b1, type="l", lend=1, col="orangered3")
  lines(a1, c1, type="l", lend=1, col="orangered3")
  lines(x2, y2, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a2, b2, type="l", lend=1, col="darkcyan")
  lines(a2, c2, type="l", lend=1, col="darkcyan")  
  lines(x3, y3, type="l", lwd=1, lend=1,col="orangered3")
  lines(a3, b3, type="l", lend=1, col="orangered3")
  lines(a3, c3, type="l", lend=1, col="orangered3")
	lines(x4, y4, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a4, b4, type="l", lend=1, col="darkcyan")
  lines(a4, c4, type="l", lend=1, col="darkcyan")
  lines(x5, y5, type="l", lwd=1, lend=1,col="orangered3")
  lines(a5, b5, type="l", lend=1, col="orangered3")
  lines(a5, c5, type="l", lend=1, col="orangered3")
	lines(x6, y6, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a6, b6, type="l", lend=1, col="darkcyan")
  lines(a6, c6, type="l", lend=1, col="darkcyan")
	lines(x7, y7, type="l", lwd=1, lend=1,col="orangered3")
  lines(a7, b7, type="l", lend=1, col="orangered3")
  lines(a7, c7, type="l", lend=1, col="orangered3")
	lines(x8, y8, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a8, b8, type="l", lend=1, col="darkcyan")
  lines(a8, c8, type="l", lend=1, col="darkcyan")
	axis(2,at=c(0,0.5,1),labels=c(0,0.5,1), padj=0.4, cex.axis=0.7)
mtext("ESCO", side=2, padj=-4, cex=0.5)

#plot 12 SURLAG
for(i in 1:8){
	assign(paste("x",i,sep=""), c(i,i))
	assign(paste("y",i,sep=""), c(Calib.Ranges[12,(2*i-1)], Calib.Ranges[12,2*i]))
  assign(paste("a",i,sep=""), c((i-0.08),(i+0.08)))
  assign(paste("b",i,sep=""), c(Calib.Ranges[12,(2*i-1)], Calib.Ranges[12,(2*i-1)]))
  assign(paste("c",i,sep=""), c(Calib.Ranges[12,2*i], Calib.Ranges[12,2*i]))
	}
	#plot(x1, y1, type="l", main="", xlab="", ylab="SURLAG", xlim=c(1,8), ylim=c(min(Calib.Ranges[12,]),max(Calib.Ranges[12,])))
plot(x1, y1, type="l", xlim=c(1,8), ylim=c(0,24), xaxt="n", yaxt="n", xlab=NA, lwd=1, lend=1, col="orangered3")
	lines(a1, b1, type="l", lend=1, col="orangered3")
  lines(a1, c1, type="l", lend=1, col="orangered3")
  lines(x2, y2, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a2, b2, type="l", lend=1, col="darkcyan")
  lines(a2, c2, type="l", lend=1, col="darkcyan")  
  lines(x3, y3, type="l", lwd=1, lend=1,col="orangered3")
  lines(a3, b3, type="l", lend=1, col="orangered3")
  lines(a3, c3, type="l", lend=1, col="orangered3")
	lines(x4, y4, type="l", lwd=1, lend=1,col="darkcyan")
	lines(a4, b4, type="l", lend=1, col="darkcyan")
  lines(a4, c4, type="l", lend=1, col="darkcyan")
  lines(x5, y5, type="l", lwd=1, lend=1,col="orangered3")
  lines(a5, b5, type="l", lend=1, col="orangered3")
  lines(a5, c5, type="l", lend=1, col="orangered3")
	lines(x6, y6, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a6, b6, type="l", lend=1, col="darkcyan")
  lines(a6, c6, type="l", lend=1, col="darkcyan")
	lines(x7, y7, type="l", lwd=1, lend=1,col="orangered3")
  lines(a7, b7, type="l", lend=1, col="orangered3")
  lines(a7, c7, type="l", lend=1, col="orangered3")
	lines(x8, y8, type="l", lwd=1, lend=1,col="darkcyan")
  lines(a8, b8, type="l", lend=1, col="darkcyan")
  lines(a8, c8, type="l", lend=1, col="darkcyan")
	axis(1,at=c(1,2,3,4,5,6,7,8),labels=c("G","R","G","R","G","R","G","R"), padj=-1, cex.axis=0.8)
  axis(2,at=c(0,10,20),labels=c(0,10,20), padj=0.4, cex.axis=0.75)
mtext("SURLAG", side=2, padj=-4, cex=0.5)
dev.off()



